image: node:14

stages:
  - build

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
